CREATE DATABASE PERSONS;
USE PERSONS;
CREATE TABLE PERSONDETAILS(
	PERSONID INT IDENTITY(1,1) PRIMARY KEY,
	LASTNAME VARCHAR(255) NOT NULL,
	fIRSTNAME VARCHAR(255) NOT NULL,
	AGE INT);

SELECT * FROM PERSONDETAILS;

INSERT INTO PERSONDETAILS(PERSONID,LASTNAME,fIRSTNAME,AGE) VALUES ('1','LAKSHMI','PRIYA','21'); 
INSERT INTO PERSONDETAILS(PERSONID,LASTNAME,fIRSTNAME,AGE) VALUES ('2','LAKSHMI','PRIYA','21'); 
INSERT INTO PERSONDETAILS VALUES('AMBRUTA','VIJI','23');

UPDATE PERSONDETAILS
SET fIRSTNAME='KIRI' 
WHERE PERSONID='1';

DELETE FROM PERSONDETAILS
WHERE PERSONID='2';

ALTER TABLE PERSONDETAILS
DROP COLUMN AGE;


TRUNCATE TABLE PERSONDETAILS;
DROP TABLE PERSONDETAILS;

create table Orders(
	orderid int IDENTITY(1,1) primary key,
	orderNumbers int not null,
	PERSONID INT FOREIGN KEY REFERENCES PERSONDETAILS(PERSONID));

SELECT * FROM ORDERS;

INSERT INTO ORDERS VALUES('1234','1');

